/**
 * Auth API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthUserEntity } from '../model/models';
import { LoginRequest } from '../model/models';
import { RegisterRequest } from '../model/models';
import { TokenResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param loginRequest 
     */
    login(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<TokenResponse>;

    /**
     * 
     * 
     * @param body 
     */
    passwordForgot(body: object, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param body 
     */
    passwordReset(body: object, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param registerRequest 
     */
    register(registerRequest: RegisterRequest, extraHttpRequestParams?: any): Observable<AuthUserEntity>;

}
