/**
 * Community API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { City } from './city';


export interface CommunityResponse { 
    id?: number;
    name?: string;
    city?: City;
}

