/**
 * Community API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEntityDto } from './userEntityDto';
import { Community } from './community';


export interface InvitationEntity { 
    id?: number;
    community?: Community;
    user?: UserEntityDto;
    code?: string;
}

