/**
 * Community API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleEntityDto } from './roleEntityDto';


export interface UserEntityDto { 
    id?: number;
    lastname?: string;
    firstname?: string;
    birthdate?: string;
    gender?: number;
    email?: string;
    password?: string;
    loggedInCommunityId?: string;
    role?: RoleEntityDto;
    createdAt?: string;
    updatedAt?: string;
}

