/**
 * Community API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Community } from '../model/models';
import { CommunityResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CommunityControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param community 
     */
    add(community: Community, extraHttpRequestParams?: any): Observable<Community>;

    /**
     * 
     * 
     */
    getAll(extraHttpRequestParams?: any): Observable<Array<Community>>;

    /**
     * 
     * 
     * @param id 
     */
    getById(id: number, extraHttpRequestParams?: any): Observable<CommunityResponse>;

}
