/**
 * Community API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { InvitationCreationRequest } from '../model/models';
import { InvitationEntity } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InvitationControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param invitationCreationRequest 
     */
    createInvitation(invitationCreationRequest: InvitationCreationRequest, extraHttpRequestParams?: any): Observable<InvitationEntity>;

    /**
     * 
     * 
     * @param id 
     */
    deleteInvitation(id: number, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * 
     * 
     * @param communityId 
     */
    getAllByCommunityId(communityId: number, extraHttpRequestParams?: any): Observable<Array<InvitationEntity>>;

    /**
     * 
     * 
     * @param code 
     * @param email 
     */
    getByCode(code: string, email: string, extraHttpRequestParams?: any): Observable<InvitationEntity>;

    /**
     * 
     * 
     * @param code 
     */
    validateInvitation(code: string, extraHttpRequestParams?: any): Observable<boolean>;

}
