/**
 * Emplacement API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Emplacement } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EmplacementControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param emplacementId 
     */
    _delete(emplacementId: number, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param emplacement 
     */
    add(emplacement: Emplacement, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param communityId 
     */
    getAllByCommunity(communityId: string, extraHttpRequestParams?: any): Observable<Array<Emplacement>>;

    /**
     * 
     * 
     * @param id 
     */
    getEmplacementById(id: number, extraHttpRequestParams?: any): Observable<Emplacement>;

}
