/**
 * Product API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Product } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProductControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param code 
     */
    addedToCommunity(code: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     */
    getAll(extraHttpRequestParams?: any): Observable<Array<Product>>;

    /**
     * 
     * 
     * @param requestBody 
     */
    getAllByIdList(requestBody: Array<string>, extraHttpRequestParams?: any): Observable<Array<Product>>;

    /**
     * 
     * 
     * @param code 
     */
    getById(code: string, extraHttpRequestParams?: any): Observable<object>;

}
