/**
 * Auth API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleEntity } from "./roleEntity"

export interface AuthUserEntity {
    id?: number
    lastname?: string
    firstname?: string
    email?: string
    password?: string
    birthdate?: string
    gender?: number
    loggedInCommunityId?: string
    role?: RoleEntity
}
