/**
 * Auth API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    lastname?: string;
    firstname?: string;
    gender?: number;
    email?: string;
    password?: string;
    invitation_code?: string;
}

