/**
 * Product to Community API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProductToCommunity } from '../model/models';
import { QuantityDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProductToCommunityControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param productEanCode 
     * @param communityId 
     */
    _delete(productEanCode: string, communityId: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param communityId 
     * @param productToCommunity 
     */
    add(communityId: string, productToCommunity: ProductToCommunity, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param communityId 
     * @param emplacementId 
     */
    countAllByCommunityByEmplacement(communityId: string, emplacementId: string, extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     */
    getAll(extraHttpRequestParams?: any): Observable<Array<ProductToCommunity>>;

    /**
     * 
     * 
     * @param communityId 
     */
    getAllByCommunity(communityId: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param communityId 
     * @param emplacementId 
     */
    getAllByCommunityByEmplacement(communityId: string, emplacementId: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param communityId 
     * @param requestBody 
     */
    massDelete(communityId: string, requestBody: Array<string>, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param communityId 
     * @param productId 
     * @param quantityDto 
     */
    updateQuantity(communityId: string, productId: string, quantityDto: QuantityDto, extraHttpRequestParams?: any): Observable<object>;

}
