/**
 * Product to Community API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PageProductToCommunity } from '../model/models';
import { ProductResponseDto } from '../model/models';
import { ProductToCommunity } from '../model/models';
import { QuantityDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProductToCommunityControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param productEanCode 
     * @param communityId 
     */
    _delete(productEanCode: string, communityId: number, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @param communityId 
     * @param productToCommunity 
     */
    add(communityId: number, productToCommunity: ProductToCommunity, extraHttpRequestParams?: any): Observable<ProductToCommunity>;

    /**
     * 
     * 
     * @param communityId 
     * @param emplacementId 
     */
    countAllByCommunityByEmplacement(communityId: number, emplacementId: number, extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     * @param filters 
     * @param page 
     * @param size 
     */
    getAll(filters: { [key: string]: string; }, page?: number, size?: number, extraHttpRequestParams?: any): Observable<PageProductToCommunity>;

    /**
     * 
     * 
     * @param communityId 
     */
    getAllByCommunity(communityId: number, extraHttpRequestParams?: any): Observable<Array<ProductResponseDto>>;

    /**
     * 
     * 
     * @param communityId 
     * @param emplacementId 
     */
    getAllByCommunityByEmplacement(communityId: number, emplacementId: number, extraHttpRequestParams?: any): Observable<Array<ProductResponseDto>>;

    /**
     * 
     * 
     * @param communityId 
     * @param requestBody 
     */
    massDelete(communityId: number, requestBody: Array<string>, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @param communityId 
     * @param productId 
     * @param quantityDto 
     */
    updateQuantity(communityId: number, productId: string, quantityDto: QuantityDto, extraHttpRequestParams?: any): Observable<ProductToCommunity>;

}
