/**
 * User API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { CommunityDto } from './communityDto';


export interface UserGetRequestDto { 
    id?: number;
    lastname?: string;
    firstname?: string;
    birthdate?: string;
    gender?: number;
    email?: string;
    loggedInCommunity?: CommunityDto;
    role?: Role;
}

