/**
 * User API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface User { 
    id?: number;
    lastname?: string;
    firstname?: string;
    birthdate?: string;
    gender?: number;
    email?: string;
    password?: string;
    loggedInCommunityId?: string;
    role?: Role;
}

