/**
 * User API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { User } from '../model/models';
import { UserAddRequestDto } from '../model/models';
import { UserGetRequestDto } from '../model/models';
import { UserLoginRequestDto } from '../model/models';
import { UserUpdateLoggedInCommunityRequestDto } from '../model/models';
import { UserUpdateRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param requestBody 
     */
    _delete(requestBody: Array<number>, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param userAddRequestDto 
     */
    add(userAddRequestDto: UserAddRequestDto, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param userUpdateLoggedInCommunityRequestDto 
     */
    communityLogin(userUpdateLoggedInCommunityRequestDto: UserUpdateLoggedInCommunityRequestDto, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * 
     * 
     * @param id 
     */
    get(id: number, extraHttpRequestParams?: any): Observable<UserGetRequestDto>;

    /**
     * 
     * 
     */
    getAll(extraHttpRequestParams?: any): Observable<Array<User>>;

    /**
     * 
     * 
     * @param email 
     */
    getByEmail(email: string, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param userLoginRequestDto 
     */
    login(userLoginRequestDto: UserLoginRequestDto, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param id 
     * @param userUpdateRequestDto 
     */
    update(id: number, userUpdateRequestDto: UserUpdateRequestDto, extraHttpRequestParams?: any): Observable<User>;

}
