/**
 * Category API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CategoryToCommunity } from '../model/models';
import { ProductToCategory } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CategoryToCommunityControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param categoryToCommunity 
     */
    add2(categoryToCommunity: CategoryToCommunity, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    getAll1(extraHttpRequestParams?: any): Observable<Array<CategoryToCommunity>>;

    /**
     * 
     * 
     * @param communityId 
     * @param categoryId 
     */
    getByCommunityIdAndCategoryId(communityId: string, categoryId: number, extraHttpRequestParams?: any): Observable<CategoryToCommunity>;

    /**
     * 
     * 
     * @param communityId 
     */
    getCategoriesByCommunityId(communityId: string, extraHttpRequestParams?: any): Observable<Array<CategoryToCommunity>>;

    /**
     * 
     * 
     * @param communityId 
     * @param qte 
     * @param productToCategory 
     */
    updatePreferenciesFactors(communityId: string, qte: number, productToCategory: Array<ProductToCategory>, extraHttpRequestParams?: any): Observable<{}>;

}
