/**
 * Category API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Category } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CategoryControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param productCode 
     * @param requestBody 
     */
    add(productCode: string, requestBody: Array<string>, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param categoryId 
     */
    get(categoryId: string, extraHttpRequestParams?: any): Observable<Category>;

    /**
     * 
     * 
     */
    getAll(extraHttpRequestParams?: any): Observable<Array<Category>>;

}
