/**
 * Category API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CategoriesDto } from '../model/models';
import { ProductToCategory } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProductToCategoryControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param productEan 
     * @param categoriesDto 
     */
    add1(productEan: string, categoriesDto: CategoriesDto, extraHttpRequestParams?: any): Observable<ProductToCategory>;

    /**
     * 
     * 
     * @param productEan 
     */
    getCategoriesIdsByProductId(productEan: string, extraHttpRequestParams?: any): Observable<Array<number>>;

    /**
     * 
     * 
     * @param categoryId 
     */
    getRandomProductByCategory(categoryId: number, extraHttpRequestParams?: any): Observable<ProductToCategory>;

    /**
     * 
     * 
     * @param categoryId 
     */
    getRelatedCategories(categoryId: number, extraHttpRequestParams?: any): Observable<Array<ProductToCategory>>;

}
