/**
 * Product to Community API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { SortObject } from './sortObject';
import { ProductToCommunity } from './productToCommunity';


export interface PageProductToCommunity { 
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<ProductToCommunity>;
    number?: number;
    sort?: SortObject;
    numberOfElements?: number;
    pageable?: PageableObject;
    first?: boolean;
    last?: boolean;
    empty?: boolean;
}

