/**
 * Product to Community API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductResponseDto { 
    name?: string;
    nbScanned?: number;
    thumbnail?: string;
    nbAdded?: number;
    quantity?: number;
    emplacementId?: number;
    eancode?: string;
}

