/**
 * Product to Community API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductToCommunity { 
    id?: number;
    productId?: string;
    communityId?: string;
    emplacementId?: string;
    qte?: number;
    createdAt?: string;
    updatedAt?: string;
}

