/**
 * User API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Role } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RoleControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param role 
     */
    add1(role: Role, extraHttpRequestParams?: any): Observable<Role>;

    /**
     * 
     * 
     */
    getAll1(extraHttpRequestParams?: any): Observable<Array<Role>>;

    /**
     * 
     * 
     * @param role 
     */
    update1(role: Role, extraHttpRequestParams?: any): Observable<Role>;

}
