/**
 * User API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CommunityDto } from '../model/models';
import { User } from '../model/models';
import { UserToCommunity } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserToCommunityControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param userToCommunity 
     */
    add2(userToCommunity: UserToCommunity, extraHttpRequestParams?: any): Observable<UserToCommunity>;

    /**
     * 
     * 
     */
    getAll2(extraHttpRequestParams?: any): Observable<Array<UserToCommunity>>;

    /**
     * 
     * 
     * @param communityId 
     */
    getAllByCommunity(communityId: number, extraHttpRequestParams?: any): Observable<Array<User>>;

    /**
     * 
     * 
     * @param userId 
     */
    getAllByUser(userId: number, extraHttpRequestParams?: any): Observable<Array<CommunityDto>>;

    /**
     * 
     * 
     * @param userToCommunity 
     */
    update2(userToCommunity: UserToCommunity, extraHttpRequestParams?: any): Observable<UserToCommunity>;

}
