/**
 * Product API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Product { 
    name?: string;
    nbScanned?: number;
    nbAdded?: number;
    thumbnail?: string;
    eancode?: string;
}

